export const BLOG_PROSE = [
  "prose max-w-none",
  "[--tw-prose-body:var(--muted-foreground)]",
  "[--tw-prose-headings:var(--foreground)]",
  "[--tw-prose-lead:var(--muted-foreground)]",
  "[--tw-prose-links:var(--primary)]",
  "[--tw-prose-bold:var(--foreground)]",
  "[--tw-prose-counters:var(--muted-foreground)]",
  "[--tw-prose-bullets:var(--primary)]",
  "[--tw-prose-hr:var(--border)]",
  "[--tw-prose-quotes:var(--foreground)]",
  "[--tw-prose-quote-borders:var(--primary)]",
  "[--tw-prose-captions:var(--muted-foreground)]",
  "[--tw-prose-code:var(--foreground)]",
  "[--tw-prose-pre-code:var(--foreground)]",
  "[--tw-prose-pre-bg:var(--muted)]",
  "[--tw-prose-th-borders:var(--border)]",
  "[--tw-prose-td-borders:var(--border)]",
  "prose-headings:font-semibold prose-headings:tracking-tight",
  "prose-h1:text-3xl prose-h2:text-2xl prose-h3:text-xl prose-h4:text-lg",
  "prose-a:font-medium prose-a:underline prose-a:underline-offset-2 hover:prose-a:text-foreground",
  "prose-blockquote:rounded-r-md prose-blockquote:bg-muted/60 prose-blockquote:py-1 prose-blockquote:pr-4 prose-blockquote:not-italic",
  "prose-code:rounded prose-code:bg-muted prose-code:px-1.5 prose-code:py-0.5 prose-code:font-mono prose-code:before:content-none prose-code:after:content-none",
  "prose-pre:rounded-lg prose-pre:border prose-pre:border-border",
  "prose-th:text-foreground",
  "prose-tables",
  "prose-img:my-5 prose-img:max-w-full prose-img:rounded-md",
  "[&_img[data-align='center']]:mx-auto [&_img[data-align='center']]:block",
  "[&_img[data-align='right']]:ml-auto [&_img[data-align='right']]:block",
  "[&_img[data-align='left']]:mr-auto [&_img[data-align='left']]:block",
  "[&_mark]:rounded-sm [&_mark]:bg-warning/40 [&_mark]:px-0.5 [&_mark]:text-foreground",
  "[&_ul[data-type='taskList']]:list-none [&_ul[data-type='taskList']]:pl-0",
  "[&_ul[data-type='taskList']_li]:flex [&_ul[data-type='taskList']_li]:items-start [&_ul[data-type='taskList']_li]:gap-2",
  "[&_ul[data-type='taskList']_li>label]:mt-1.5 [&_ul[data-type='taskList']_li>div]:flex-1",
  "[&_ul[data-type='taskList']_p]:my-1",
  "[&_iframe]:aspect-video [&_iframe]:h-auto [&_iframe]:w-full [&_iframe]:rounded-lg",
  "[&_[style*='text-align:center']]:text-center [&_[style*='text-align:right']]:text-right [&_[style*='text-align:justify']]:text-justify",
].join(" ");
